/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package Integracion.Esquemas.Referencias;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class GeoReferencia extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6157136319625299205L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GeoReferencia\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"fields\":[{\"name\":\"latitud\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"longitud\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"altura\",\"type\":[\"null\",\"double\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<GeoReferencia> ENCODER =
      new BinaryMessageEncoder<GeoReferencia>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<GeoReferencia> DECODER =
      new BinaryMessageDecoder<GeoReferencia>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<GeoReferencia> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<GeoReferencia> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<GeoReferencia> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<GeoReferencia>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this GeoReferencia to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a GeoReferencia from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a GeoReferencia instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static GeoReferencia fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.Double latitud;
   private java.lang.Double longitud;
   private java.lang.Double altura;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public GeoReferencia() {}

  /**
   * All-args constructor.
   * @param latitud The new value for latitud
   * @param longitud The new value for longitud
   * @param altura The new value for altura
   */
  public GeoReferencia(java.lang.Double latitud, java.lang.Double longitud, java.lang.Double altura) {
    this.latitud = latitud;
    this.longitud = longitud;
    this.altura = altura;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return latitud;
    case 1: return longitud;
    case 2: return altura;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: latitud = (java.lang.Double)value$; break;
    case 1: longitud = (java.lang.Double)value$; break;
    case 2: altura = (java.lang.Double)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'latitud' field.
   * @return The value of the 'latitud' field.
   */
  public java.lang.Double getLatitud() {
    return latitud;
  }


  /**
   * Sets the value of the 'latitud' field.
   * @param value the value to set.
   */
  public void setLatitud(java.lang.Double value) {
    this.latitud = value;
  }

  /**
   * Gets the value of the 'longitud' field.
   * @return The value of the 'longitud' field.
   */
  public java.lang.Double getLongitud() {
    return longitud;
  }


  /**
   * Sets the value of the 'longitud' field.
   * @param value the value to set.
   */
  public void setLongitud(java.lang.Double value) {
    this.longitud = value;
  }

  /**
   * Gets the value of the 'altura' field.
   * @return The value of the 'altura' field.
   */
  public java.lang.Double getAltura() {
    return altura;
  }


  /**
   * Sets the value of the 'altura' field.
   * @param value the value to set.
   */
  public void setAltura(java.lang.Double value) {
    this.altura = value;
  }

  /**
   * Creates a new GeoReferencia RecordBuilder.
   * @return A new GeoReferencia RecordBuilder
   */
  public static Integracion.Esquemas.Referencias.GeoReferencia.Builder newBuilder() {
    return new Integracion.Esquemas.Referencias.GeoReferencia.Builder();
  }

  /**
   * Creates a new GeoReferencia RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new GeoReferencia RecordBuilder
   */
  public static Integracion.Esquemas.Referencias.GeoReferencia.Builder newBuilder(Integracion.Esquemas.Referencias.GeoReferencia.Builder other) {
    if (other == null) {
      return new Integracion.Esquemas.Referencias.GeoReferencia.Builder();
    } else {
      return new Integracion.Esquemas.Referencias.GeoReferencia.Builder(other);
    }
  }

  /**
   * Creates a new GeoReferencia RecordBuilder by copying an existing GeoReferencia instance.
   * @param other The existing instance to copy.
   * @return A new GeoReferencia RecordBuilder
   */
  public static Integracion.Esquemas.Referencias.GeoReferencia.Builder newBuilder(Integracion.Esquemas.Referencias.GeoReferencia other) {
    if (other == null) {
      return new Integracion.Esquemas.Referencias.GeoReferencia.Builder();
    } else {
      return new Integracion.Esquemas.Referencias.GeoReferencia.Builder(other);
    }
  }

  /**
   * RecordBuilder for GeoReferencia instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GeoReferencia>
    implements org.apache.avro.data.RecordBuilder<GeoReferencia> {

    private java.lang.Double latitud;
    private java.lang.Double longitud;
    private java.lang.Double altura;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Integracion.Esquemas.Referencias.GeoReferencia.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.latitud)) {
        this.latitud = data().deepCopy(fields()[0].schema(), other.latitud);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.longitud)) {
        this.longitud = data().deepCopy(fields()[1].schema(), other.longitud);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.altura)) {
        this.altura = data().deepCopy(fields()[2].schema(), other.altura);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing GeoReferencia instance
     * @param other The existing instance to copy.
     */
    private Builder(Integracion.Esquemas.Referencias.GeoReferencia other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.latitud)) {
        this.latitud = data().deepCopy(fields()[0].schema(), other.latitud);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.longitud)) {
        this.longitud = data().deepCopy(fields()[1].schema(), other.longitud);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.altura)) {
        this.altura = data().deepCopy(fields()[2].schema(), other.altura);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'latitud' field.
      * @return The value.
      */
    public java.lang.Double getLatitud() {
      return latitud;
    }


    /**
      * Sets the value of the 'latitud' field.
      * @param value The value of 'latitud'.
      * @return This builder.
      */
    public Integracion.Esquemas.Referencias.GeoReferencia.Builder setLatitud(java.lang.Double value) {
      validate(fields()[0], value);
      this.latitud = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'latitud' field has been set.
      * @return True if the 'latitud' field has been set, false otherwise.
      */
    public boolean hasLatitud() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'latitud' field.
      * @return This builder.
      */
    public Integracion.Esquemas.Referencias.GeoReferencia.Builder clearLatitud() {
      latitud = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'longitud' field.
      * @return The value.
      */
    public java.lang.Double getLongitud() {
      return longitud;
    }


    /**
      * Sets the value of the 'longitud' field.
      * @param value The value of 'longitud'.
      * @return This builder.
      */
    public Integracion.Esquemas.Referencias.GeoReferencia.Builder setLongitud(java.lang.Double value) {
      validate(fields()[1], value);
      this.longitud = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'longitud' field has been set.
      * @return True if the 'longitud' field has been set, false otherwise.
      */
    public boolean hasLongitud() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'longitud' field.
      * @return This builder.
      */
    public Integracion.Esquemas.Referencias.GeoReferencia.Builder clearLongitud() {
      longitud = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'altura' field.
      * @return The value.
      */
    public java.lang.Double getAltura() {
      return altura;
    }


    /**
      * Sets the value of the 'altura' field.
      * @param value The value of 'altura'.
      * @return This builder.
      */
    public Integracion.Esquemas.Referencias.GeoReferencia.Builder setAltura(java.lang.Double value) {
      validate(fields()[2], value);
      this.altura = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'altura' field has been set.
      * @return True if the 'altura' field has been set, false otherwise.
      */
    public boolean hasAltura() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'altura' field.
      * @return This builder.
      */
    public Integracion.Esquemas.Referencias.GeoReferencia.Builder clearAltura() {
      altura = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public GeoReferencia build() {
      try {
        GeoReferencia record = new GeoReferencia();
        record.latitud = fieldSetFlags()[0] ? this.latitud : (java.lang.Double) defaultValue(fields()[0]);
        record.longitud = fieldSetFlags()[1] ? this.longitud : (java.lang.Double) defaultValue(fields()[1]);
        record.altura = fieldSetFlags()[2] ? this.altura : (java.lang.Double) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<GeoReferencia>
    WRITER$ = (org.apache.avro.io.DatumWriter<GeoReferencia>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<GeoReferencia>
    READER$ = (org.apache.avro.io.DatumReader<GeoReferencia>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.latitud == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeDouble(this.latitud);
    }

    if (this.longitud == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeDouble(this.longitud);
    }

    if (this.altura == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeDouble(this.altura);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.latitud = null;
      } else {
        this.latitud = in.readDouble();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.longitud = null;
      } else {
        this.longitud = in.readDouble();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.altura = null;
      } else {
        this.altura = in.readDouble();
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.latitud = null;
          } else {
            this.latitud = in.readDouble();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.longitud = null;
          } else {
            this.longitud = in.readDouble();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.altura = null;
          } else {
            this.altura = in.readDouble();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










