/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package Integracion.Esquemas.Referencias;
@org.apache.avro.specific.AvroGenerated
public enum TipoDeDocumento implements org.apache.avro.generic.GenericEnumSymbol<TipoDeDocumento> {
  undefined, DNI, CUIT, CUIL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TipoDeDocumento\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"symbols\":[\"undefined\",\"DNI\",\"CUIT\",\"CUIL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
