/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package Integracion.Esquemas.Referencias;
@org.apache.avro.specific.AvroGenerated
public enum TipoDeTelefono implements org.apache.avro.generic.GenericEnumSymbol<TipoDeTelefono> {
  trabajo, celular, casa, otro  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TipoDeTelefono\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"symbols\":[\"trabajo\",\"celular\",\"casa\",\"otro\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
