/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package Integracion.Esquemas;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Traza extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8268242439401669395L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Traza\",\"namespace\":\"Integracion.Esquemas\",\"fields\":[{\"name\":\"codigoDeEnvio\",\"type\":\"string\"},{\"name\":\"nombre\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"cuando\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"codigoDeContratoInterno\",\"type\":\"string\"},{\"name\":\"estadoDelEnvio\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"cicloDelEnvio\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"operador\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"estadoDeLaRendicion\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"comentario\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"sucursalAsociadaAlEvento\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"DatosSucursal\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"fields\":[{\"name\":\"codigo\",\"type\":\"string\"},{\"name\":\"nombre\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"id\",\"type\":\"string\"}]}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();
static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<Traza> ENCODER =
      new BinaryMessageEncoder<Traza>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Traza> DECODER =
      new BinaryMessageDecoder<Traza>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Traza> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Traza> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Traza> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Traza>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Traza to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Traza from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Traza instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Traza fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence codigoDeEnvio;
   private java.lang.CharSequence nombre;
   private java.time.Instant cuando;
   private java.lang.CharSequence codigoDeContratoInterno;
   private java.lang.CharSequence estadoDelEnvio;
   private java.lang.CharSequence cicloDelEnvio;
   private java.lang.CharSequence operador;
   private java.lang.CharSequence estadoDeLaRendicion;
   private java.lang.CharSequence comentario;
   private Integracion.Esquemas.Referencias.DatosSucursal sucursalAsociadaAlEvento;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Traza() {}

  /**
   * All-args constructor.
   * @param codigoDeEnvio The new value for codigoDeEnvio
   * @param nombre The new value for nombre
   * @param cuando The new value for cuando
   * @param codigoDeContratoInterno The new value for codigoDeContratoInterno
   * @param estadoDelEnvio The new value for estadoDelEnvio
   * @param cicloDelEnvio The new value for cicloDelEnvio
   * @param operador The new value for operador
   * @param estadoDeLaRendicion The new value for estadoDeLaRendicion
   * @param comentario The new value for comentario
   * @param sucursalAsociadaAlEvento The new value for sucursalAsociadaAlEvento
   */
  public Traza(java.lang.CharSequence codigoDeEnvio, java.lang.CharSequence nombre, java.time.Instant cuando, java.lang.CharSequence codigoDeContratoInterno, java.lang.CharSequence estadoDelEnvio, java.lang.CharSequence cicloDelEnvio, java.lang.CharSequence operador, java.lang.CharSequence estadoDeLaRendicion, java.lang.CharSequence comentario, Integracion.Esquemas.Referencias.DatosSucursal sucursalAsociadaAlEvento) {
    this.codigoDeEnvio = codigoDeEnvio;
    this.nombre = nombre;
    this.cuando = cuando.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.codigoDeContratoInterno = codigoDeContratoInterno;
    this.estadoDelEnvio = estadoDelEnvio;
    this.cicloDelEnvio = cicloDelEnvio;
    this.operador = operador;
    this.estadoDeLaRendicion = estadoDeLaRendicion;
    this.comentario = comentario;
    this.sucursalAsociadaAlEvento = sucursalAsociadaAlEvento;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return codigoDeEnvio;
    case 1: return nombre;
    case 2: return cuando;
    case 3: return codigoDeContratoInterno;
    case 4: return estadoDelEnvio;
    case 5: return cicloDelEnvio;
    case 6: return operador;
    case 7: return estadoDeLaRendicion;
    case 8: return comentario;
    case 9: return sucursalAsociadaAlEvento;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: codigoDeEnvio = (java.lang.CharSequence)value$; break;
    case 1: nombre = (java.lang.CharSequence)value$; break;
    case 2: cuando = (java.time.Instant)value$; break;
    case 3: codigoDeContratoInterno = (java.lang.CharSequence)value$; break;
    case 4: estadoDelEnvio = (java.lang.CharSequence)value$; break;
    case 5: cicloDelEnvio = (java.lang.CharSequence)value$; break;
    case 6: operador = (java.lang.CharSequence)value$; break;
    case 7: estadoDeLaRendicion = (java.lang.CharSequence)value$; break;
    case 8: comentario = (java.lang.CharSequence)value$; break;
    case 9: sucursalAsociadaAlEvento = (Integracion.Esquemas.Referencias.DatosSucursal)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'codigoDeEnvio' field.
   * @return The value of the 'codigoDeEnvio' field.
   */
  public java.lang.CharSequence getCodigoDeEnvio() {
    return codigoDeEnvio;
  }


  /**
   * Sets the value of the 'codigoDeEnvio' field.
   * @param value the value to set.
   */
  public void setCodigoDeEnvio(java.lang.CharSequence value) {
    this.codigoDeEnvio = value;
  }

  /**
   * Gets the value of the 'nombre' field.
   * @return The value of the 'nombre' field.
   */
  public java.lang.CharSequence getNombre() {
    return nombre;
  }


  /**
   * Sets the value of the 'nombre' field.
   * @param value the value to set.
   */
  public void setNombre(java.lang.CharSequence value) {
    this.nombre = value;
  }

  /**
   * Gets the value of the 'cuando' field.
   * @return The value of the 'cuando' field.
   */
  public java.time.Instant getCuando() {
    return cuando;
  }


  /**
   * Sets the value of the 'cuando' field.
   * @param value the value to set.
   */
  public void setCuando(java.time.Instant value) {
    this.cuando = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'codigoDeContratoInterno' field.
   * @return The value of the 'codigoDeContratoInterno' field.
   */
  public java.lang.CharSequence getCodigoDeContratoInterno() {
    return codigoDeContratoInterno;
  }


  /**
   * Sets the value of the 'codigoDeContratoInterno' field.
   * @param value the value to set.
   */
  public void setCodigoDeContratoInterno(java.lang.CharSequence value) {
    this.codigoDeContratoInterno = value;
  }

  /**
   * Gets the value of the 'estadoDelEnvio' field.
   * @return The value of the 'estadoDelEnvio' field.
   */
  public java.lang.CharSequence getEstadoDelEnvio() {
    return estadoDelEnvio;
  }


  /**
   * Sets the value of the 'estadoDelEnvio' field.
   * @param value the value to set.
   */
  public void setEstadoDelEnvio(java.lang.CharSequence value) {
    this.estadoDelEnvio = value;
  }

  /**
   * Gets the value of the 'cicloDelEnvio' field.
   * @return The value of the 'cicloDelEnvio' field.
   */
  public java.lang.CharSequence getCicloDelEnvio() {
    return cicloDelEnvio;
  }


  /**
   * Sets the value of the 'cicloDelEnvio' field.
   * @param value the value to set.
   */
  public void setCicloDelEnvio(java.lang.CharSequence value) {
    this.cicloDelEnvio = value;
  }

  /**
   * Gets the value of the 'operador' field.
   * @return The value of the 'operador' field.
   */
  public java.lang.CharSequence getOperador() {
    return operador;
  }


  /**
   * Sets the value of the 'operador' field.
   * @param value the value to set.
   */
  public void setOperador(java.lang.CharSequence value) {
    this.operador = value;
  }

  /**
   * Gets the value of the 'estadoDeLaRendicion' field.
   * @return The value of the 'estadoDeLaRendicion' field.
   */
  public java.lang.CharSequence getEstadoDeLaRendicion() {
    return estadoDeLaRendicion;
  }


  /**
   * Sets the value of the 'estadoDeLaRendicion' field.
   * @param value the value to set.
   */
  public void setEstadoDeLaRendicion(java.lang.CharSequence value) {
    this.estadoDeLaRendicion = value;
  }

  /**
   * Gets the value of the 'comentario' field.
   * @return The value of the 'comentario' field.
   */
  public java.lang.CharSequence getComentario() {
    return comentario;
  }


  /**
   * Sets the value of the 'comentario' field.
   * @param value the value to set.
   */
  public void setComentario(java.lang.CharSequence value) {
    this.comentario = value;
  }

  /**
   * Gets the value of the 'sucursalAsociadaAlEvento' field.
   * @return The value of the 'sucursalAsociadaAlEvento' field.
   */
  public Integracion.Esquemas.Referencias.DatosSucursal getSucursalAsociadaAlEvento() {
    return sucursalAsociadaAlEvento;
  }


  /**
   * Sets the value of the 'sucursalAsociadaAlEvento' field.
   * @param value the value to set.
   */
  public void setSucursalAsociadaAlEvento(Integracion.Esquemas.Referencias.DatosSucursal value) {
    this.sucursalAsociadaAlEvento = value;
  }

  /**
   * Creates a new Traza RecordBuilder.
   * @return A new Traza RecordBuilder
   */
  public static Integracion.Esquemas.Traza.Builder newBuilder() {
    return new Integracion.Esquemas.Traza.Builder();
  }

  /**
   * Creates a new Traza RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Traza RecordBuilder
   */
  public static Integracion.Esquemas.Traza.Builder newBuilder(Integracion.Esquemas.Traza.Builder other) {
    if (other == null) {
      return new Integracion.Esquemas.Traza.Builder();
    } else {
      return new Integracion.Esquemas.Traza.Builder(other);
    }
  }

  /**
   * Creates a new Traza RecordBuilder by copying an existing Traza instance.
   * @param other The existing instance to copy.
   * @return A new Traza RecordBuilder
   */
  public static Integracion.Esquemas.Traza.Builder newBuilder(Integracion.Esquemas.Traza other) {
    if (other == null) {
      return new Integracion.Esquemas.Traza.Builder();
    } else {
      return new Integracion.Esquemas.Traza.Builder(other);
    }
  }

  /**
   * RecordBuilder for Traza instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Traza>
    implements org.apache.avro.data.RecordBuilder<Traza> {

    private java.lang.CharSequence codigoDeEnvio;
    private java.lang.CharSequence nombre;
    private java.time.Instant cuando;
    private java.lang.CharSequence codigoDeContratoInterno;
    private java.lang.CharSequence estadoDelEnvio;
    private java.lang.CharSequence cicloDelEnvio;
    private java.lang.CharSequence operador;
    private java.lang.CharSequence estadoDeLaRendicion;
    private java.lang.CharSequence comentario;
    private Integracion.Esquemas.Referencias.DatosSucursal sucursalAsociadaAlEvento;
    private Integracion.Esquemas.Referencias.DatosSucursal.Builder sucursalAsociadaAlEventoBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Integracion.Esquemas.Traza.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.codigoDeEnvio)) {
        this.codigoDeEnvio = data().deepCopy(fields()[0].schema(), other.codigoDeEnvio);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.nombre)) {
        this.nombre = data().deepCopy(fields()[1].schema(), other.nombre);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.cuando)) {
        this.cuando = data().deepCopy(fields()[2].schema(), other.cuando);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.codigoDeContratoInterno)) {
        this.codigoDeContratoInterno = data().deepCopy(fields()[3].schema(), other.codigoDeContratoInterno);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.estadoDelEnvio)) {
        this.estadoDelEnvio = data().deepCopy(fields()[4].schema(), other.estadoDelEnvio);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.cicloDelEnvio)) {
        this.cicloDelEnvio = data().deepCopy(fields()[5].schema(), other.cicloDelEnvio);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.operador)) {
        this.operador = data().deepCopy(fields()[6].schema(), other.operador);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.estadoDeLaRendicion)) {
        this.estadoDeLaRendicion = data().deepCopy(fields()[7].schema(), other.estadoDeLaRendicion);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.comentario)) {
        this.comentario = data().deepCopy(fields()[8].schema(), other.comentario);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.sucursalAsociadaAlEvento)) {
        this.sucursalAsociadaAlEvento = data().deepCopy(fields()[9].schema(), other.sucursalAsociadaAlEvento);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (other.hasSucursalAsociadaAlEventoBuilder()) {
        this.sucursalAsociadaAlEventoBuilder = Integracion.Esquemas.Referencias.DatosSucursal.newBuilder(other.getSucursalAsociadaAlEventoBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing Traza instance
     * @param other The existing instance to copy.
     */
    private Builder(Integracion.Esquemas.Traza other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.codigoDeEnvio)) {
        this.codigoDeEnvio = data().deepCopy(fields()[0].schema(), other.codigoDeEnvio);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.nombre)) {
        this.nombre = data().deepCopy(fields()[1].schema(), other.nombre);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.cuando)) {
        this.cuando = data().deepCopy(fields()[2].schema(), other.cuando);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.codigoDeContratoInterno)) {
        this.codigoDeContratoInterno = data().deepCopy(fields()[3].schema(), other.codigoDeContratoInterno);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.estadoDelEnvio)) {
        this.estadoDelEnvio = data().deepCopy(fields()[4].schema(), other.estadoDelEnvio);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.cicloDelEnvio)) {
        this.cicloDelEnvio = data().deepCopy(fields()[5].schema(), other.cicloDelEnvio);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.operador)) {
        this.operador = data().deepCopy(fields()[6].schema(), other.operador);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.estadoDeLaRendicion)) {
        this.estadoDeLaRendicion = data().deepCopy(fields()[7].schema(), other.estadoDeLaRendicion);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.comentario)) {
        this.comentario = data().deepCopy(fields()[8].schema(), other.comentario);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.sucursalAsociadaAlEvento)) {
        this.sucursalAsociadaAlEvento = data().deepCopy(fields()[9].schema(), other.sucursalAsociadaAlEvento);
        fieldSetFlags()[9] = true;
      }
      this.sucursalAsociadaAlEventoBuilder = null;
    }

    /**
      * Gets the value of the 'codigoDeEnvio' field.
      * @return The value.
      */
    public java.lang.CharSequence getCodigoDeEnvio() {
      return codigoDeEnvio;
    }


    /**
      * Sets the value of the 'codigoDeEnvio' field.
      * @param value The value of 'codigoDeEnvio'.
      * @return This builder.
      */
    public Integracion.Esquemas.Traza.Builder setCodigoDeEnvio(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.codigoDeEnvio = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'codigoDeEnvio' field has been set.
      * @return True if the 'codigoDeEnvio' field has been set, false otherwise.
      */
    public boolean hasCodigoDeEnvio() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'codigoDeEnvio' field.
      * @return This builder.
      */
    public Integracion.Esquemas.Traza.Builder clearCodigoDeEnvio() {
      codigoDeEnvio = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'nombre' field.
      * @return The value.
      */
    public java.lang.CharSequence getNombre() {
      return nombre;
    }


    /**
      * Sets the value of the 'nombre' field.
      * @param value The value of 'nombre'.
      * @return This builder.
      */
    public Integracion.Esquemas.Traza.Builder setNombre(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.nombre = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'nombre' field has been set.
      * @return True if the 'nombre' field has been set, false otherwise.
      */
    public boolean hasNombre() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'nombre' field.
      * @return This builder.
      */
    public Integracion.Esquemas.Traza.Builder clearNombre() {
      nombre = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'cuando' field.
      * @return The value.
      */
    public java.time.Instant getCuando() {
      return cuando;
    }


    /**
      * Sets the value of the 'cuando' field.
      * @param value The value of 'cuando'.
      * @return This builder.
      */
    public Integracion.Esquemas.Traza.Builder setCuando(java.time.Instant value) {
      validate(fields()[2], value);
      this.cuando = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'cuando' field has been set.
      * @return True if the 'cuando' field has been set, false otherwise.
      */
    public boolean hasCuando() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'cuando' field.
      * @return This builder.
      */
    public Integracion.Esquemas.Traza.Builder clearCuando() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'codigoDeContratoInterno' field.
      * @return The value.
      */
    public java.lang.CharSequence getCodigoDeContratoInterno() {
      return codigoDeContratoInterno;
    }


    /**
      * Sets the value of the 'codigoDeContratoInterno' field.
      * @param value The value of 'codigoDeContratoInterno'.
      * @return This builder.
      */
    public Integracion.Esquemas.Traza.Builder setCodigoDeContratoInterno(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.codigoDeContratoInterno = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'codigoDeContratoInterno' field has been set.
      * @return True if the 'codigoDeContratoInterno' field has been set, false otherwise.
      */
    public boolean hasCodigoDeContratoInterno() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'codigoDeContratoInterno' field.
      * @return This builder.
      */
    public Integracion.Esquemas.Traza.Builder clearCodigoDeContratoInterno() {
      codigoDeContratoInterno = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'estadoDelEnvio' field.
      * @return The value.
      */
    public java.lang.CharSequence getEstadoDelEnvio() {
      return estadoDelEnvio;
    }


    /**
      * Sets the value of the 'estadoDelEnvio' field.
      * @param value The value of 'estadoDelEnvio'.
      * @return This builder.
      */
    public Integracion.Esquemas.Traza.Builder setEstadoDelEnvio(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.estadoDelEnvio = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'estadoDelEnvio' field has been set.
      * @return True if the 'estadoDelEnvio' field has been set, false otherwise.
      */
    public boolean hasEstadoDelEnvio() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'estadoDelEnvio' field.
      * @return This builder.
      */
    public Integracion.Esquemas.Traza.Builder clearEstadoDelEnvio() {
      estadoDelEnvio = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'cicloDelEnvio' field.
      * @return The value.
      */
    public java.lang.CharSequence getCicloDelEnvio() {
      return cicloDelEnvio;
    }


    /**
      * Sets the value of the 'cicloDelEnvio' field.
      * @param value The value of 'cicloDelEnvio'.
      * @return This builder.
      */
    public Integracion.Esquemas.Traza.Builder setCicloDelEnvio(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.cicloDelEnvio = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'cicloDelEnvio' field has been set.
      * @return True if the 'cicloDelEnvio' field has been set, false otherwise.
      */
    public boolean hasCicloDelEnvio() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'cicloDelEnvio' field.
      * @return This builder.
      */
    public Integracion.Esquemas.Traza.Builder clearCicloDelEnvio() {
      cicloDelEnvio = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'operador' field.
      * @return The value.
      */
    public java.lang.CharSequence getOperador() {
      return operador;
    }


    /**
      * Sets the value of the 'operador' field.
      * @param value The value of 'operador'.
      * @return This builder.
      */
    public Integracion.Esquemas.Traza.Builder setOperador(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.operador = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'operador' field has been set.
      * @return True if the 'operador' field has been set, false otherwise.
      */
    public boolean hasOperador() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'operador' field.
      * @return This builder.
      */
    public Integracion.Esquemas.Traza.Builder clearOperador() {
      operador = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'estadoDeLaRendicion' field.
      * @return The value.
      */
    public java.lang.CharSequence getEstadoDeLaRendicion() {
      return estadoDeLaRendicion;
    }


    /**
      * Sets the value of the 'estadoDeLaRendicion' field.
      * @param value The value of 'estadoDeLaRendicion'.
      * @return This builder.
      */
    public Integracion.Esquemas.Traza.Builder setEstadoDeLaRendicion(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.estadoDeLaRendicion = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'estadoDeLaRendicion' field has been set.
      * @return True if the 'estadoDeLaRendicion' field has been set, false otherwise.
      */
    public boolean hasEstadoDeLaRendicion() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'estadoDeLaRendicion' field.
      * @return This builder.
      */
    public Integracion.Esquemas.Traza.Builder clearEstadoDeLaRendicion() {
      estadoDeLaRendicion = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'comentario' field.
      * @return The value.
      */
    public java.lang.CharSequence getComentario() {
      return comentario;
    }


    /**
      * Sets the value of the 'comentario' field.
      * @param value The value of 'comentario'.
      * @return This builder.
      */
    public Integracion.Esquemas.Traza.Builder setComentario(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.comentario = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'comentario' field has been set.
      * @return True if the 'comentario' field has been set, false otherwise.
      */
    public boolean hasComentario() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'comentario' field.
      * @return This builder.
      */
    public Integracion.Esquemas.Traza.Builder clearComentario() {
      comentario = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'sucursalAsociadaAlEvento' field.
      * @return The value.
      */
    public Integracion.Esquemas.Referencias.DatosSucursal getSucursalAsociadaAlEvento() {
      return sucursalAsociadaAlEvento;
    }


    /**
      * Sets the value of the 'sucursalAsociadaAlEvento' field.
      * @param value The value of 'sucursalAsociadaAlEvento'.
      * @return This builder.
      */
    public Integracion.Esquemas.Traza.Builder setSucursalAsociadaAlEvento(Integracion.Esquemas.Referencias.DatosSucursal value) {
      validate(fields()[9], value);
      this.sucursalAsociadaAlEventoBuilder = null;
      this.sucursalAsociadaAlEvento = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'sucursalAsociadaAlEvento' field has been set.
      * @return True if the 'sucursalAsociadaAlEvento' field has been set, false otherwise.
      */
    public boolean hasSucursalAsociadaAlEvento() {
      return fieldSetFlags()[9];
    }

    /**
     * Gets the Builder instance for the 'sucursalAsociadaAlEvento' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public Integracion.Esquemas.Referencias.DatosSucursal.Builder getSucursalAsociadaAlEventoBuilder() {
      if (sucursalAsociadaAlEventoBuilder == null) {
        if (hasSucursalAsociadaAlEvento()) {
          setSucursalAsociadaAlEventoBuilder(Integracion.Esquemas.Referencias.DatosSucursal.newBuilder(sucursalAsociadaAlEvento));
        } else {
          setSucursalAsociadaAlEventoBuilder(Integracion.Esquemas.Referencias.DatosSucursal.newBuilder());
        }
      }
      return sucursalAsociadaAlEventoBuilder;
    }

    /**
     * Sets the Builder instance for the 'sucursalAsociadaAlEvento' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public Integracion.Esquemas.Traza.Builder setSucursalAsociadaAlEventoBuilder(Integracion.Esquemas.Referencias.DatosSucursal.Builder value) {
      clearSucursalAsociadaAlEvento();
      sucursalAsociadaAlEventoBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'sucursalAsociadaAlEvento' field has an active Builder instance
     * @return True if the 'sucursalAsociadaAlEvento' field has an active Builder instance
     */
    public boolean hasSucursalAsociadaAlEventoBuilder() {
      return sucursalAsociadaAlEventoBuilder != null;
    }

    /**
      * Clears the value of the 'sucursalAsociadaAlEvento' field.
      * @return This builder.
      */
    public Integracion.Esquemas.Traza.Builder clearSucursalAsociadaAlEvento() {
      sucursalAsociadaAlEvento = null;
      sucursalAsociadaAlEventoBuilder = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Traza build() {
      try {
        Traza record = new Traza();
        record.codigoDeEnvio = fieldSetFlags()[0] ? this.codigoDeEnvio : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.nombre = fieldSetFlags()[1] ? this.nombre : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.cuando = fieldSetFlags()[2] ? this.cuando : (java.time.Instant) defaultValue(fields()[2]);
        record.codigoDeContratoInterno = fieldSetFlags()[3] ? this.codigoDeContratoInterno : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.estadoDelEnvio = fieldSetFlags()[4] ? this.estadoDelEnvio : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.cicloDelEnvio = fieldSetFlags()[5] ? this.cicloDelEnvio : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.operador = fieldSetFlags()[6] ? this.operador : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.estadoDeLaRendicion = fieldSetFlags()[7] ? this.estadoDeLaRendicion : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.comentario = fieldSetFlags()[8] ? this.comentario : (java.lang.CharSequence) defaultValue(fields()[8]);
        if (sucursalAsociadaAlEventoBuilder != null) {
          try {
            record.sucursalAsociadaAlEvento = this.sucursalAsociadaAlEventoBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("sucursalAsociadaAlEvento"));
            throw e;
          }
        } else {
          record.sucursalAsociadaAlEvento = fieldSetFlags()[9] ? this.sucursalAsociadaAlEvento : (Integracion.Esquemas.Referencias.DatosSucursal) defaultValue(fields()[9]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Traza>
    WRITER$ = (org.apache.avro.io.DatumWriter<Traza>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Traza>
    READER$ = (org.apache.avro.io.DatumReader<Traza>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










